apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app1-tugas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app1-tugas
    spec:
      containers:
      - name: app-workshop
        image: dharafibri/workshoptcc:v1
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata: 
  name: service1-tugas
spec: 
  ports: 
     -  port: 8000
        protocol: TCP
        targetPort: 8000
  selector: 
    app: app1-tugas
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app2-tugas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: app2-tugas
    spec:
      containers:
      - name: app-workshop
        image: dharafibri/workshoptcc:v1
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata: 
  name: service2-tugas
spec: 
  ports: 
     -  port: 8000
        protocol: TCP
        targetPort: 8000
  selector: 
    app: app2-tugas
  type: ClusterIP
